### ISSUE TITLE
Bug while expanding nodes with more than 32766 children - v3

### ISSUE THREAD

**Issue by sirgallifrey** [Lodin/react-vtree#52] opened 2021-01-29 16:44 UTC
Frist of all, thanks for the amazing work put into the lib. It's very awesome.

Conditions for reproducing:

- You need to have a node (lets call A) with 32767 children or more (do not know if they need to be direct children, I think not)
- And you need to have one of more nodes after node A.
- All my testing was done in latest chrome, using windows 10 and MacOs

I prepared a reproduction of the bug here: https://github.com/sirgallifrey/react-vtree/tree/openning-lots-of-nodes

How to reproduce:

- Checkout my fork on the branch called: `openning-lots-of-nodes`
- run storybook:dev script
- Go to story called `Big List Issue`
- Scroll all the way to the bottom and observe that everything renders properly so far.
- Scroll back up and collapse the node called `Root.2`
- Observe that everything still works as expected.
- Expand the node called `Root.2` and scroll all the way to the bottom
- Observe that some nodes appear missing, some may be duplicated.
- From now on, collapsing and expanding `Root.2` will not fix the issue.
- Collapsing and then expanding the node `Root` will fix the issue end render everything properly, but issue can comeback by expanding `Root.2`

There is one extra glitch that I'm seeing in this reproduction that I didn't saw when I first used the lib: If you keep collapsing and expanding `Root.2` you will end up with a ghost floating element that will not go away even by collapsing and expanding the parent. But the following workaround prevents that

Workaround:

Since opening the root node fixes the issue, it is possible to use `recomputeTree` instead of `setOpen` and always open the root node with every instruction, an example of the workaround can be found on my fork, in the story named: `Big List Issue workaround`

I didn't had time yet to try find the bug on the code, but since the issue happens at such specific number of itens it's probably happening inside the `updateExistingTree` https://github.com/Lodin/react-vtree/blob/master/src/Tree.tsx#L402

Pictures / videos:

https://user-images.githubusercontent.com/2331645/106302660-881ac800-6259-11eb-8e29-8965973707e7.mov

![Screen Shot 2021-01-29 at 17 36 53](https://user-images.githubusercontent.com/2331645/106302704-94068a00-6259-11eb-84aa-33a17b4850da.png)

**Comment by Lodin** [comment] 2021-03-03 07:24
It looks like a duplicate of #48. I'll take a look if it is not fixed after the #54 is merged.

**Comment by Lodin** [comment] 2021-03-03 07:25
Thanks for the filling the issue, btw. Sorry for the late response, I'm kind of busy in the latest couple of months.

**Comment by sirgallifrey** [comment] 2021-03-03 07:54
No worries, I'm just happy this project exists, nice work! :)

**Comment by Lodin** [comment] 2021-03-20 18:47
Fixed in #54

**Comment by Lodin** [comment] 2021-03-20 19:16
Released in react-vtree@3.0.0-beta.1. Note that now you need to use the beta tag to install the 3.0.0 version because I have released 3.0.0-beta.0 as latest by mistake.

**Comment by sirgallifrey** [comment] 2021-03-22 09:49
Hello @Lodin I merged the new changes on my reproduction branch and the issue is still reproducible https://github.com/sirgallifrey/react-vtree/tree/openning-lots-of-nodes

I'll give a shot at trying to fix it

**Comment by Lodin** [comment] 2021-04-30 19:18
Hey, @sirgallifrey. I think I fixed the bug: that was a miscalculation in the array length. Could you please check if the [`fix/max-args-bug`](https://github.com/Lodin/react-vtree/tree/fix/max-args-bug) branch works for you?

**Comment by sirgallifrey** [comment] 2021-04-30 19:31
@Lodin Have you seen my PR?

**Comment by Lodin** [comment] 2021-04-30 19:41
Oh, yes, sorry, should have answered there as well.

**Comment by sirgallifrey** [comment] 2021-04-30 19:41
@Lodin your fix is very similar to mine, no sure which one is best. In my PR I have some unit tests you can try with your solution

**Comment by Lodin** [comment] 2021-04-30 20:00
@sirgallifrey ok, I missed the main part, sorry 😓 Let me take a closer look then.

**Comment by sirgallifrey** [comment] 2021-04-30 20:43
No worries, my only concern is to have the bug fixed, I don't care if it's my solution or not :) I'm sure you will do the best for the project

**Comment by kirsi** [comment] 2021-06-25 12:45
@Lodin Hey, what's the status on the fix? Could you release a new version with it? With beta.1 we still have the issue. Thanks for the great library and other than this small issue, it works like a charm...

**Closed** 2021-07-24 20:00 UTC
Labels: bug
